// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvltikzvyynfbfajxaqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2bHRpa3p2eXluZmJmYWp4YXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzcyMTYsImV4cCI6MjA2ODE1MzIxNn0.TdPYPtMLq_YmrOv8H04q2oire_uec-kX0LWcHBRyyr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});